resource "aws_iam_instance_profile" "main" {
  name = "${var.name}Profile"
  path = "${var.path}"
  role = "${aws_iam_role.main.name}"
}

resource "aws_iam_role" "main" {
  name               = "${var.name}"
  path               = "${var.path}"
  description        = "Role assigned to the ${var.name}Profile instance profile (generated by Terraform)"
  assume_role_policy = var.assume_role_policy
  tags               = "${var.tags}"
}


resource "aws_iam_policy" "user_policies" {
  name        = "${var.name}Policy-${count.index}"
  path        = "${var.path}"
  description = "User-managed policy assigned to the ${var.name}Role role (generated by Terraform)"
  policy      = "${var.policy[count.index]}"
  count       = "${length(var.policy)}"
}

resource "aws_iam_role_policy_attachment" "user_policies" {
  role       = "${aws_iam_role.main.name}"
  policy_arn = "${element(aws_iam_policy.user_policies.*.arn, count.index)}"
  count      = "${length(var.policy)}"
}

resource "aws_iam_role_policy_attachment" "ssm_policy" {
  role       = "${aws_iam_role.main.name}"
  policy_arn = "${var.policy_arns[count.index]}"
  count      = "${var.attach_ssm_policy ? 1 : 0}"
}


